### ISSUE TITLE
storage xss

### ISSUE THREAD

**Issue by durkworf** [dedetech/DedeCMSv5#2]
When adding friendship links, a storage XSS is generated, which is，located in the background - [module] - [friendship links].
1、	Discovered in uploads/dede/friendlink_add.php
 `    $query = "INSERT INTO `#@__flink`(sortrank,url,webname,logo,msg,email,typeid,dtime,ischeck)
 VALUES('$sortrank','$url','$webname','$imgurl','$msg','$email','$typeid','$dtime','$ischeck'); ";`
Call the SQL statement and insert $email into the database
2、	Flnk.php is called in uploads/dede/friendlink_main.html to filter the $mail parameter simply
 `	<div style="float:right;padding-right:6px;">
		[<a href="friendlink_add.php"><u>增加链接</u></a>]
 	 	[<a href="friendlink_type.php"><u>网站类型管理</u></a>]
  	[<a href='{dede:global name='cfg_phpurl' /}/flink.php' target='_blank'><u>友情链接预览</u></a>]
  </div>`
It was found that only the htmlspecialchars () function was invoked to convert the predefined characters "<" (less) and ">" (greater) into HTML entities: a simple escape storage was carried out, while the contents of $mail were not strictly filtered and escaped to HTML encoding.
3、	Tests show that malicious characters are stored in the database.
4、	When clicking on the change, the friendlink_edit.php file is invoked, while the friendlinl_edit.php does not filter out the queried $mail directly to produce a storage cross-station.
$myLink = $dsql->GetOne("SELECT #@__flink.*,#@__flinktype.typename FROM #@__flink LEFT JOIN #@__flinktype ON #@__flink.typeid=#@__flinktype.id WHERE #@__flink.id=$id");
Implementation process
5、	Log in to the background of the website and click on [Module]-[Friendship Link]
6、	Increasing Friendship Links
7、	Enter malicious code at the webmaster's email and click on Submit to store it in the database.
123123"/><img src=1 onerror=alert(/许仙/)/>
8、	Click on Change to Discover XSS .

**Comment by llgoer** [comment]
I found the main problem is to make restrictions on the file /plus/flink_add.php to prevent XSS intruding. I have fixed it now, thanks for the submission.
